data:
  # raw_data_path: "../data/raw/manet_routing_data.csv"    # for EDA
  raw_data_path: "data/raw/manet_routing_data.csv"    # To run the main.py
  processed_data_path: "data/processed/processed_manet_data.csv"
  target_column: "Network_Performance_Class"
  test_size: 0.2
  random_state: 42
  # Columns to be one-hot encoded
  categorical_features:
    - "mobility_model"
    - "routing_protocol"
    - "traffic_type"

model:
  name: "RandomForestClassifier"
  params:
    n_estimators: 100
    random_state: 42
    class_weight: "balanced" # Useful for imbalanced classes if any

paths:
  model_save_path: "models/trained_model.pkl"
  figure_save_dir: "reports/figures/"